'use strict';
Object.defineProperty(exports, '__esModule', {value: true});
exports.TxType = void 0;
var TxType;
(function(TxType) {
    TxType['SEND'] = '0x01';
    TxType['SELL'] = '0x02';
    TxType['SELL_ALL'] = '0x03';
    TxType['BUY'] = '0x04';
    TxType['CREATE_COIN'] = '0x05';
    TxType['DECLARE_CANDIDACY'] = '0x06';
    TxType['DELEGATE'] = '0x07';
    TxType['UNBOND'] = '0x08';
    TxType['REDEEM_CHECK'] = '0x09';
    TxType['SET_CANDIDATE_ON'] = '0x0A';
    TxType['SET_CANDIDATE_OFF'] = '0x0B';
    TxType['CREATE_MULTISIG'] = '0x0C';
    TxType['MULTISEND'] = '0x0D';
    TxType['EDIT_CANDIDATE'] = '0x0E';
    TxType['SET_HALT_BLOCK'] = '0x0F';
    TxType['RECREATE_COIN'] = '0x10';
    TxType['EDIT_TICKER_OWNER'] = '0x11';
    TxType['EDIT_MULTISIG'] = '0x12';
    TxType['PRICE_VOTE'] = '0x13';
    TxType['EDIT_CANDIDATE_PUBLIC_KEY'] = '0x14';
    TxType['ADD_LIQUIDITY'] = '0x15';
    TxType['REMOVE_LIQUIDITY'] = '0x16';
    TxType['SELL_SWAP_POOL'] = '0x17';
    TxType['BUY_SWAP_POOL'] = '0x18';
    TxType['SELL_ALL_SWAP_POOL'] = '0x19';
    TxType['EDIT_CANDIDATE_COMMISSION'] = '0x1A';
    TxType['MOVE_STAKE'] = '0x1B';
    TxType['MINT_TOKEN'] = '0x1C';
    TxType['BURN_TOKEN'] = '0x1D';
    TxType['CREATE_TOKEN'] = '0x1E';
    TxType['RECREATE_TOKEN'] = '0x1F';
    TxType['VOTE_COMMISSION'] = '0x20';
    TxType['VOTE_UPDATE'] = '0x21';
    TxType['CREATE_SWAP_POOL'] = '0x22';
})(TxType = exports.TxType || (exports.TxType = {}));
