declare const assertIsBuffer: (input: any, msg?: string | Error) => void;
declare const assertIsString: (input: any, msg?: string | Error) => void;
declare const assertIsArray: (input: any, msg?: string | Error) => void;
declare const assertIsNumber: (input: any, msg?: string | Error) => void;
declare const assertIsInt: (input: any, msg?: string | Error) => void;
declare const assertIsPositiveInt: (input: any, msg?: string | Error) => void;
declare const assertIsHexString: (input: string, msg?: string | Error) => void;
declare const assertIsMinerAddress: (input: string, msg?: string | Error) => void;
declare const assertIsMinerPublicKey: (input: string, msg?: string | Error) => void;
declare const assertIsMinerTransaction: (input: string, msg?: string | Error) => void;
declare const assertIsMnemonic: (input: string, msg?: string | Error) => void;
export { assertIsBuffer, assertIsString, assertIsNumber, assertIsInt, assertIsPositiveInt, assertIsArray, assertIsHexString, assertIsMinerAddress, assertIsMinerPublicKey, assertIsMinerTransaction, assertIsMnemonic, };
