"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.assertIsMnemonic = exports.assertIsMinerTransaction = exports.assertIsMinerPublicKey = exports.assertIsMinerAddress = exports.assertIsHexString = exports.assertIsArray = exports.assertIsPositiveInt = exports.assertIsInt = exports.assertIsNumber = exports.assertIsString = exports.assertIsBuffer = void 0;
const external_1 = require("../external");
const type_1 = require("./type");
const prefix_1 = require("./prefix");
const assertIsBuffer = (input, msg) => external_1.assert(type_1.isBuffer(input), msg || `Only supports Buffer but input was: ${input}`);
exports.assertIsBuffer = assertIsBuffer;
const assertIsString = (input, msg) => external_1.assert(type_1.isString(input), msg || `Only supports strings but input was: ${input}`);
exports.assertIsString = assertIsString;
const assertIsArray = (input, msg) => external_1.assert(type_1.isArray(input), msg || `Only supports number arrays but input was: ${input}`);
exports.assertIsArray = assertIsArray;
const assertIsNumber = (input, msg) => external_1.assert(type_1.isNumber(input), msg || `Only supports number but input was: ${input}`);
exports.assertIsNumber = assertIsNumber;
const assertIsInt = (input, msg) => external_1.assert(type_1.isInteger(input), msg || `Only supports integer number but input was: ${input}`);
exports.assertIsInt = assertIsInt;
const assertIsPositiveInt = (input, msg) => external_1.assert(type_1.isInteger(input) && 0 <= input, msg || `Only supports positive integer number but input was: ${input}`);
exports.assertIsPositiveInt = assertIsPositiveInt;
const assertIsHexString = (input, msg) => external_1.assert(type_1.isHexString(input), msg || `Only supports 0x-prefixed hex strings but input was: ${input}`);
exports.assertIsHexString = assertIsHexString;
const assertIsMinerAddress = (input, msg) => external_1.assert(prefix_1.isValidAddress(input), msg || `Only supports Mx-prefixed hex strings but input was: ${input}`);
exports.assertIsMinerAddress = assertIsMinerAddress;
const assertIsMinerPublicKey = (input, msg) => external_1.assert(prefix_1.isValidPublicKey(input), msg || `Only supports Mp-prefixed hex strings but input was: ${input}`);
exports.assertIsMinerPublicKey = assertIsMinerPublicKey;
const assertIsMinerTransaction = (input, msg) => external_1.assert(prefix_1.isValidTransaction(input), msg || `Only supports Mt-prefixed hex strings but input was: ${input}`);
exports.assertIsMinerTransaction = assertIsMinerTransaction;
const assertIsMnemonic = (input, msg) => external_1.assert(external_1.isValidMnemonic(input), msg || `Invalid bip39 mnemonic. Expect 12+ dictionary valid words but input was: ${input}`);
exports.assertIsMnemonic = assertIsMnemonic;
